[tool.black]
line-length = 110
target-version = ['py38']

[tool.poetry]
name = 'acceptance'
version = '0.0.0'
description = 'Not used'
authors = []

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
pytest = "7.1.2"
c2cwsgiutils = "5.0.0"
boltons = "21.0.0"
netifaces = "0.11.0"
requests = "2.28.1"
lxml = "4.9.0"
