[tool.black]
line-length = 110
target-version = ['py38']

[tool.poetry]
name = 'acceptance'
version = '0.0.0'
description = 'Not used'
authors = []

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
pytest = "7.1.3"
c2cwsgiutils = "5.1.7"
boltons = "21.0.0"
netifaces = "0.11.0"
requests = "2.31.0"
lxml = "4.9.3"
certifi = "2023.7.22"
OWSLib = "0.29.2"
urllib3 = "2.0.6"
