[tool.black]
line-length = 110
target-version = ["py312"]

[tool.isort]
profile = "black"
line_length = 110

[tool.mypy]
python_version = "3.12"
pretty = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unused_configs = true
disallow_untyped_defs = true
strict_optional = true
strict = true

[tool.poetry]
name = 'acceptance'
version = '0.0.0'
description = 'Not used'
authors = []

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pytest = "8.2.0"
c2cwsgiutils = "6.0.8"
boltons = "24.0.0"
netifaces = "0.11.0"
requests = "2.31.0"
lxml = "5.2.1"
certifi = "2024.2.2"
OWSLib = "0.30.0"
